// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(awvalid,0,0);
        VL_OUT8(awready,0,0);
        VL_IN8(wstrb,3,0);
        VL_IN8(wvalid,0,0);
        VL_OUT8(wready,0,0);
        VL_OUT8(bresp,1,0);
        VL_OUT8(bvalid,0,0);
        VL_IN8(bready,0,0);
        VL_IN8(arvalid,0,0);
        VL_OUT8(arready,0,0);
        VL_OUT8(rresp,1,0);
        VL_OUT8(rvalid,0,0);
        VL_IN8(rready,0,0);
        VL_OUT8(uart_tx,0,0);
        VL_IN8(uart_rx,0,0);
        VL_OUT8(timer_irq,0,0);
        CData/*0:0*/ axi_subsystem__DOT__clk;
        CData/*0:0*/ axi_subsystem__DOT__rst_n;
        CData/*0:0*/ axi_subsystem__DOT__awvalid;
        CData/*0:0*/ axi_subsystem__DOT__awready;
        CData/*3:0*/ axi_subsystem__DOT__wstrb;
        CData/*0:0*/ axi_subsystem__DOT__wvalid;
        CData/*0:0*/ axi_subsystem__DOT__wready;
        CData/*1:0*/ axi_subsystem__DOT__bresp;
        CData/*0:0*/ axi_subsystem__DOT__bvalid;
        CData/*0:0*/ axi_subsystem__DOT__bready;
        CData/*0:0*/ axi_subsystem__DOT__arvalid;
        CData/*0:0*/ axi_subsystem__DOT__arready;
        CData/*1:0*/ axi_subsystem__DOT__rresp;
        CData/*0:0*/ axi_subsystem__DOT__rvalid;
        CData/*0:0*/ axi_subsystem__DOT__rready;
        CData/*0:0*/ axi_subsystem__DOT__uart_tx;
        CData/*0:0*/ axi_subsystem__DOT__uart_rx;
        CData/*0:0*/ axi_subsystem__DOT__timer_irq;
        CData/*3:0*/ axi_subsystem__DOT__s_awvalid;
        CData/*3:0*/ axi_subsystem__DOT__s_awready;
        SData/*15:0*/ axi_subsystem__DOT__s_wstrb;
        CData/*3:0*/ axi_subsystem__DOT__s_wvalid;
        CData/*3:0*/ axi_subsystem__DOT__s_wready;
        CData/*7:0*/ axi_subsystem__DOT__s_bresp;
        CData/*3:0*/ axi_subsystem__DOT__s_bvalid;
        CData/*3:0*/ axi_subsystem__DOT__s_bready;
        CData/*3:0*/ axi_subsystem__DOT__s_arvalid;
        CData/*3:0*/ axi_subsystem__DOT__s_arready;
        CData/*7:0*/ axi_subsystem__DOT__s_rresp;
        CData/*3:0*/ axi_subsystem__DOT__s_rvalid;
        CData/*3:0*/ axi_subsystem__DOT__s_rready;
        CData/*0:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_awvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_awready;
        CData/*3:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_wstrb;
        CData/*0:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_wvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_wready;
        CData/*1:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_bresp;
        CData/*0:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_bvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_bready;
        CData/*0:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_arvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_arready;
        CData/*1:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_rresp;
        CData/*0:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_rvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_rready;
        CData/*3:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_awvalid;
        CData/*3:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_awready;
    };
    struct {
        SData/*15:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_wstrb;
        CData/*3:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_wvalid;
        CData/*3:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_wready;
        CData/*7:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_bresp;
        CData/*3:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_bvalid;
        CData/*3:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_bready;
        CData/*3:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_arvalid;
        CData/*3:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_arready;
        CData/*7:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_rresp;
        CData/*3:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_rvalid;
        CData/*3:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_rready;
        CData/*1:0*/ axi_subsystem__DOT__u_interconnect__DOT__write_sel;
        CData/*1:0*/ axi_subsystem__DOT__u_interconnect__DOT__read_sel;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__clk;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__rst_n;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__awvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__awready;
        CData/*3:0*/ axi_subsystem__DOT__u_ram__DOT__wstrb;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__wvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__wready;
        CData/*1:0*/ axi_subsystem__DOT__u_ram__DOT__bresp;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__bvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__bready;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__arvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__arready;
        CData/*1:0*/ axi_subsystem__DOT__u_ram__DOT__rresp;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__rvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_ram__DOT__rready;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__clk;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__rst_n;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__awvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__awready;
        CData/*3:0*/ axi_subsystem__DOT__u_uart__DOT__wstrb;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__wvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__wready;
        CData/*1:0*/ axi_subsystem__DOT__u_uart__DOT__bresp;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__bvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__bready;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__arvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__arready;
        CData/*1:0*/ axi_subsystem__DOT__u_uart__DOT__rresp;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__rvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__rready;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__tx;
        CData/*0:0*/ axi_subsystem__DOT__u_uart__DOT__rx;
        CData/*7:0*/ axi_subsystem__DOT__u_uart__DOT__tx_data;
        CData/*7:0*/ axi_subsystem__DOT__u_uart__DOT__rx_data;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__clk;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__rst_n;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__awvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__awready;
        CData/*3:0*/ axi_subsystem__DOT__u_timer__DOT__wstrb;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__wvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__wready;
        CData/*1:0*/ axi_subsystem__DOT__u_timer__DOT__bresp;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__bvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__bready;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__arvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__arready;
        CData/*1:0*/ axi_subsystem__DOT__u_timer__DOT__rresp;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__rvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__rready;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__irq;
        CData/*0:0*/ axi_subsystem__DOT__u_timer__DOT__active;
    };
    struct {
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__clk;
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__rst_n;
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__awvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__awready;
        CData/*3:0*/ axi_subsystem__DOT__u_gpio__DOT__wstrb;
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__wvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__wready;
        CData/*1:0*/ axi_subsystem__DOT__u_gpio__DOT__bresp;
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__bvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__bready;
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__arvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__arready;
        CData/*1:0*/ axi_subsystem__DOT__u_gpio__DOT__rresp;
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__rvalid;
        CData/*0:0*/ axi_subsystem__DOT__u_gpio__DOT__rready;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__axi_subsystem__DOT__u_ram__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__axi_subsystem__DOT__u_ram__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__axi_subsystem__DOT__u_uart__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__axi_subsystem__DOT__u_uart__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__axi_subsystem__DOT__u_timer__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__axi_subsystem__DOT__u_timer__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__axi_subsystem__DOT__u_gpio__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__axi_subsystem__DOT__u_gpio__DOT__rst_n__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*9:0*/ axi_subsystem__DOT__u_ram__DOT__mem_addr;
        VL_IN(awaddr,31,0);
        VL_IN(wdata,31,0);
        VL_IN(araddr,31,0);
        VL_OUT(rdata,31,0);
        VL_INOUT(gpio_pins,31,0);
        IData/*31:0*/ axi_subsystem__DOT__awaddr;
        IData/*31:0*/ axi_subsystem__DOT__wdata;
        IData/*31:0*/ axi_subsystem__DOT__araddr;
        IData/*31:0*/ axi_subsystem__DOT__rdata;
        IData/*31:0*/ axi_subsystem__DOT__gpio_pins;
        VlWide<4>/*127:0*/ axi_subsystem__DOT__s_awaddr;
        VlWide<4>/*127:0*/ axi_subsystem__DOT__s_wdata;
        VlWide<4>/*127:0*/ axi_subsystem__DOT__s_araddr;
        VlWide<4>/*127:0*/ axi_subsystem__DOT__s_rdata;
        IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_awaddr;
        IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_wdata;
        IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_araddr;
        IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__m_rdata;
        VlWide<4>/*127:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_awaddr;
        VlWide<4>/*127:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_wdata;
        VlWide<4>/*127:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_araddr;
        VlWide<4>/*127:0*/ axi_subsystem__DOT__u_interconnect__DOT__s_rdata;
        IData/*31:0*/ axi_subsystem__DOT__u_ram__DOT__awaddr;
        IData/*31:0*/ axi_subsystem__DOT__u_ram__DOT__wdata;
        IData/*31:0*/ axi_subsystem__DOT__u_ram__DOT__araddr;
        IData/*31:0*/ axi_subsystem__DOT__u_ram__DOT__rdata;
        IData/*31:0*/ axi_subsystem__DOT__u_ram__DOT__reg_control;
        IData/*31:0*/ axi_subsystem__DOT__u_ram__DOT__reg_status;
        IData/*31:0*/ axi_subsystem__DOT__u_ram__DOT__reg_address;
        IData/*31:0*/ axi_subsystem__DOT__u_uart__DOT__awaddr;
        IData/*31:0*/ axi_subsystem__DOT__u_uart__DOT__wdata;
        IData/*31:0*/ axi_subsystem__DOT__u_uart__DOT__araddr;
        IData/*31:0*/ axi_subsystem__DOT__u_uart__DOT__rdata;
        IData/*31:0*/ axi_subsystem__DOT__u_uart__DOT__reg_ctrl;
    };
    struct {
        IData/*31:0*/ axi_subsystem__DOT__u_uart__DOT__reg_status;
        IData/*31:0*/ axi_subsystem__DOT__u_timer__DOT__awaddr;
        IData/*31:0*/ axi_subsystem__DOT__u_timer__DOT__wdata;
        IData/*31:0*/ axi_subsystem__DOT__u_timer__DOT__araddr;
        IData/*31:0*/ axi_subsystem__DOT__u_timer__DOT__rdata;
        IData/*31:0*/ axi_subsystem__DOT__u_timer__DOT__reg_ctrl;
        IData/*31:0*/ axi_subsystem__DOT__u_timer__DOT__reg_status;
        IData/*31:0*/ axi_subsystem__DOT__u_timer__DOT__reg_count;
        IData/*31:0*/ axi_subsystem__DOT__u_timer__DOT__reg_compare;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__awaddr;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__wdata;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__araddr;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__rdata;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__reg_dir;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__reg_out;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__reg_in;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out0;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out1;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out2;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out3;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out4;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out5;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out6;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out7;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out8;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out9;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out10;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out11;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out12;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out13;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out14;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out15;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out16;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out17;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out18;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out19;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out20;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out21;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out22;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out23;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out24;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out25;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out26;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out27;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out28;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out29;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out30;
        IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__gpio_pins__out__strong__out31;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<IData/*31:0*/, 1024> axi_subsystem__DOT__u_ram__DOT__mem;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr CData/*3:0*/ axi_subsystem__DOT__u_uart__DOT__CTRL_OFFSET = 0U;
    static constexpr CData/*3:0*/ axi_subsystem__DOT__u_uart__DOT__STATUS_OFFSET = 4U;
    static constexpr CData/*3:0*/ axi_subsystem__DOT__u_uart__DOT__TXDATA_OFFSET = 8U;
    static constexpr CData/*3:0*/ axi_subsystem__DOT__u_uart__DOT__RXDATA_OFFSET = 0x0cU;
    static constexpr CData/*3:0*/ axi_subsystem__DOT__u_timer__DOT__CTRL_OFFSET = 0U;
    static constexpr CData/*3:0*/ axi_subsystem__DOT__u_timer__DOT__STATUS_OFFSET = 4U;
    static constexpr CData/*3:0*/ axi_subsystem__DOT__u_timer__DOT__COUNT_OFFSET = 8U;
    static constexpr CData/*3:0*/ axi_subsystem__DOT__u_timer__DOT__COMPARE_OFFSET = 0x0cU;
    static constexpr CData/*3:0*/ axi_subsystem__DOT__u_gpio__DOT__DIR_OFFSET = 0U;
    static constexpr CData/*3:0*/ axi_subsystem__DOT__u_gpio__DOT__OUT_OFFSET = 4U;
    static constexpr CData/*3:0*/ axi_subsystem__DOT__u_gpio__DOT__IN_OFFSET = 8U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__ADDR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__NUM_SLAVES = 4U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__ADDR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__NUM_SLAVES = 4U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__RAM_END = 0x0000ffffU;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__UART_BASE = 0x40000000U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__UART_END = 0x40000fffU;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__TIMER_BASE = 0x40010000U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__TIMER_END = 0x40010fffU;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__GPIO_BASE = 0x40020000U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_interconnect__DOT__GPIO_END = 0x40020fffU;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_ram__DOT__ADDR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_ram__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_ram__DOT__MEM_DEPTH = 0x00000400U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_ram__DOT__IDX_WIDTH = 0x0000000aU;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_uart__DOT__ADDR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_uart__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_timer__DOT__ADDR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_timer__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__ADDR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ axi_subsystem__DOT__u_gpio__DOT__NUM_PINS = 0x00000020U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
