TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../rtl/axi/axi_lite_slave.sv
TOPLEVEL = axi_lite_slave
MODULE = test_axi_lite

SIM = verilator

include $(shell cocotb-config --makefiles)/Makefile.sim